# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 185177c06476b63e6309bfd5339c3bb86b5784488a9b469c567892357f5cea25df2e704c9debd22e52be1756b11bbdf455c133b73906f89ac611ee966d2f30db

test:
  secret_key_base: b3e08c91f951d24737389e65c0e8bf4896809b464d648289b726e8aaa4288854dcbd2a22fbe920bf18abc0d710891eb95c0e4005c43df7ad708a0c48a4f2dfa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
